/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dropjuancho1.pkg2;

/**
 *
 * @author juant
 */
public class dropJuancho extends javax.swing.JFrame {

    /**
     * Creates new form dropJuancho
     */
    public dropJuancho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        show_precioFinal = new javax.swing.JLabel();
        gradient = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        show_resumen = new javax.swing.JPanel();
        costoProductotxt = new javax.swing.JLabel();
        costoProductotxt1 = new javax.swing.JLabel();
        costoProductotxt2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        show_costoProducto = new javax.swing.JLabel();
        show_envioEnvio = new javax.swing.JLabel();
        show_costoAdmin = new javax.swing.JLabel();
        show_CPA = new javax.swing.JLabel();
        costoProductotxt7 = new javax.swing.JLabel();
        costoProductotxt8 = new javax.swing.JLabel();
        show_utilidad = new javax.swing.JLabel();
        show_porcentajeUtilidad = new javax.swing.JLabel();
        costoProductotxt3 = new javax.swing.JLabel();
        show_costosTotales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colors/DropJuancho (1).png"))); // NOI18N
        bg.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESE EL COSTO DEL PRODUCTO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setText("CALCULAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRECIO FINAL");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 356, 270, 30));

        show_precioFinal.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        show_precioFinal.setForeground(new java.awt.Color(0, 0, 0));
        show_precioFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_precioFinal.setText("0");
        show_precioFinal.setToolTipText("");
        bg.add(show_precioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 270, 40));

        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colors/luke-chesser-pJadQetzTkI-unsplash.jpg"))); // NOI18N
        gradient.setToolTipText("");
        bg.add(gradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resumen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 271, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        show_resumen.setBackground(new java.awt.Color(255, 255, 255));

        costoProductotxt.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt.setText("COSTO DE PRODUCTO");

        costoProductotxt1.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt1.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoProductotxt1.setText("VALOR ENVIO");

        costoProductotxt2.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt2.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoProductotxt2.setText("COSTO ADMIN");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CPA");

        show_costoProducto.setBackground(new java.awt.Color(0, 0, 0));
        show_costoProducto.setForeground(new java.awt.Color(0, 0, 0));
        show_costoProducto.setText("--------");

        show_envioEnvio.setBackground(new java.awt.Color(0, 0, 0));
        show_envioEnvio.setForeground(new java.awt.Color(0, 0, 0));
        show_envioEnvio.setText("--------");

        show_costoAdmin.setBackground(new java.awt.Color(0, 0, 0));
        show_costoAdmin.setForeground(new java.awt.Color(0, 0, 0));
        show_costoAdmin.setText("--------");

        show_CPA.setBackground(new java.awt.Color(0, 0, 0));
        show_CPA.setForeground(new java.awt.Color(0, 0, 0));
        show_CPA.setText("--------");

        costoProductotxt7.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt7.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt7.setText("UTILIDAD");

        costoProductotxt8.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt8.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt8.setText("% UTILIDAD");

        show_utilidad.setBackground(new java.awt.Color(0, 0, 0));
        show_utilidad.setForeground(new java.awt.Color(0, 0, 0));
        show_utilidad.setText("--------");

        show_porcentajeUtilidad.setBackground(new java.awt.Color(0, 0, 0));
        show_porcentajeUtilidad.setForeground(new java.awt.Color(0, 0, 0));
        show_porcentajeUtilidad.setText("--------");

        costoProductotxt3.setBackground(new java.awt.Color(0, 0, 0));
        costoProductotxt3.setForeground(new java.awt.Color(0, 0, 0));
        costoProductotxt3.setText("COSTOS TOTALES");

        show_costosTotales.setBackground(new java.awt.Color(0, 0, 0));
        show_costosTotales.setForeground(new java.awt.Color(0, 0, 0));
        show_costosTotales.setText("--------");

        javax.swing.GroupLayout show_resumenLayout = new javax.swing.GroupLayout(show_resumen);
        show_resumen.setLayout(show_resumenLayout);
        show_resumenLayout.setHorizontalGroup(
            show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_resumenLayout.createSequentialGroup()
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costoProductotxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costoProductotxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costoProductotxt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(show_costoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(show_envioEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_costoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_CPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoProductotxt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costoProductotxt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(show_resumenLayout.createSequentialGroup()
                        .addComponent(show_utilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(show_porcentajeUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show_resumenLayout.createSequentialGroup()
                .addComponent(costoProductotxt3)
                .addGap(18, 18, 18)
                .addComponent(show_costosTotales, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(458, 458, 458))
        );
        show_resumenLayout.setVerticalGroup(
            show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show_resumenLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(show_costoProducto)
                    .addComponent(costoProductotxt7)
                    .addComponent(show_utilidad)
                    .addComponent(costoProductotxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoProductotxt1)
                    .addComponent(show_envioEnvio)
                    .addComponent(costoProductotxt8)
                    .addComponent(show_porcentajeUtilidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoProductotxt2)
                    .addComponent(show_costoAdmin))
                .addGap(18, 18, 18)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(show_CPA))
                .addGap(63, 63, 63)
                .addGroup(show_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoProductotxt3)
                    .addComponent(show_costosTotales))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        bg.add(show_resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 540, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dropJuancho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dropJuancho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dropJuancho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dropJuancho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dropJuancho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel costoProductotxt;
    private javax.swing.JLabel costoProductotxt1;
    private javax.swing.JLabel costoProductotxt2;
    private javax.swing.JLabel costoProductotxt3;
    private javax.swing.JLabel costoProductotxt7;
    private javax.swing.JLabel costoProductotxt8;
    private javax.swing.JLabel gradient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel show_CPA;
    private javax.swing.JLabel show_costoAdmin;
    private javax.swing.JLabel show_costoProducto;
    private javax.swing.JLabel show_costosTotales;
    private javax.swing.JLabel show_envioEnvio;
    private javax.swing.JLabel show_porcentajeUtilidad;
    private javax.swing.JLabel show_precioFinal;
    private javax.swing.JPanel show_resumen;
    private javax.swing.JLabel show_utilidad;
    // End of variables declaration//GEN-END:variables
}
